FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Eventos API

API de eventos

## Evento [/eventos]

### Listar os eventos [GET]

Listar os eventos

+ Response 200 (application/json)

        [
            {
                "nome": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z"
            }
        ]

### Criar novo evento [POST]

Criar um novo evento

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Atualizar um evento [PUT]

Atualizar um evento

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Excluir um evento [DELETE]

Excluir um evento

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": "Favourite programming language?",
                "nome": "evento 1"
            }

## Inscrição [/inscricao]

### Listar os inscrições [GET]

Listar os Inscrições

+ Response 200 (application/json)

        [
            {
                "nome": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z"
            }
        ]

### Criar nova inscrição [POST]

Criar um novo inscrição

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Atualizar um inscrição [PUT]

Atualizar um evento

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Excluir um inscrição [DELETE]

Excluir um evento

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": "Favourite programming language?",
                "nome": "evento 1"
            }
            
## Usuário [/usuario]

### Listar os usuario [GET]

Listar os usuario

+ Response 200 (application/json)

        [
            {
                "nome": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z"
            }
        ]

### Criar nova usuario [POST]

Criar um novo usuario

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Atualizar um usuario [PUT]

Atualizar um usuario

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "nome": "Favourite programming language?",
                "data": "2015-08-05T08:40:51.620Z"
            }
            
### Excluir um usuario [DELETE]

Excluir um usuario

+ Request (application/json)

        {
            "nome": "Favourite programming language?",
            "data": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /evento/1

    + Body

            {
                "id": "Favourite programming language?",
                "nome": "evento 1"
            }